def build_handover(evidence_count: int = 0, memory_count: int = 0) -> str:
    return f"""# AIOS Habit Handover

Generated by `aios-habit handover build`.

## State
- CLI implemented.
- Evidence records: {evidence_count}
- Memory units: {memory_count}

## Commands
Run `aios-habit status`, `aios-habit audit`, and `aios-habit phase validate --phase N`.

## Recovery
Use git/history backups. Destructive operations require dry-run first.

## Next Actions
Review evidence, promote verified memory only with evidence, and audit exports before use.
"""
