def build_profile_text(name: str, items: list[dict]) -> str:
    body = f"# {name}\n\n"
    body += "Generated by `aios-habit profile build`. Unsupported claims remain UNKNOWN.\n\n"
    if not items:
        body += "- UNKNOWN: no verified export-allowed memory yet.\n"
        return body

    for memory in items:
        evidence = ", ".join(memory.get("evidence_ids", []))
        body += f"- {memory['statement']} Evidence: {evidence}\n"
    return body
