"""F1: error_cases public API."""
from .column_map import (
    COLUMN_MAP,
    GREEN_SKIP_RGB,
    HISTORY_29_MAP,
    SHEET_TYPES,
    col_letter,
    history_no_dvd,
    is_green_skip,
    is_positive_mark,
    normalize_history_row,
    normalize_row,
)
from .completeness import (
    F3B_THRESHOLD,
    measure as measure_completeness,
    report as completeness_report,
)
from .glossary import (
    PARSERS,
    import_glossary,
    init_glossary,
    lookup as glossary_lookup,
    norm_code,
)
from .import_history import (
    SHEET_NAME as HISTORY_SHEET_NAME,
    import_history,
)
from .import_lsu_logs import (
    DIALECTS as LSU_LOG_DIALECTS,
    detect_lsu_dialect,
    import_lsu_log,
    import_lsu_tree,
    read_lsu_events,
)
from .investigation_tree import (
    BRANCH_LABELS_VI,
    BRANCHES,
    ChecklistItem,
    InvestigationTree,
    WhyNode,
    build_tree,
    build_why_chain,
    export_markdown,
    render_markdown,
)
from .store import (
    batch_stats,
    connect,
    count_cases,
    finish_batch,
    get_case,
    init_db,
    sha256_file,
    start_batch,
    upsert_case,
)
from .trend_analysis import (
    DIMENSION_LABELS_VI,
    DIMENSIONS,
    MISSING_GROUP,
    Alert,
    bucket_key,
    bucketize,
    check_thresholds,
    detect_rising_trend,
    fetch_records,
    generate_report,
    group_by_dimension,
    incidence_table,
    run_periodic_report,
)
from .auto_classifier import (
    Classification,
    HistoryMatch,
    RecurrenceAlert,
    classify_error,
    classify_new_error,
    detect_family,
    detect_recurrence,
    evaluate_accuracy,
    match_history,
)
from .feedback_loop import (
    ClosureBlockedError,
    close_case,
    get_closure,
    init_feedback_loop,
    log_suggestion_call,
    positive_rate_by_quarter,
    rating_coverage,
    record_rating,
)

__all__ = [
    "COLUMN_MAP",
    "GREEN_SKIP_RGB",
    "HISTORY_29_MAP",
    "SHEET_TYPES",
    "col_letter",
    "history_no_dvd",
    "is_green_skip",
    "is_positive_mark",
    "normalize_history_row",
    "normalize_row",
    "F3B_THRESHOLD",
    "measure_completeness",
    "completeness_report",
    "PARSERS",
    "import_glossary",
    "init_glossary",
    "glossary_lookup",
    "norm_code",
    "HISTORY_SHEET_NAME",
    "import_history",
    "LSU_LOG_DIALECTS",
    "detect_lsu_dialect",
    "import_lsu_log",
    "import_lsu_tree",
    "read_lsu_events",
    "BRANCH_LABELS_VI",
    "BRANCHES",
    "ChecklistItem",
    "InvestigationTree",
    "WhyNode",
    "build_tree",
    "build_why_chain",
    "export_markdown",
    "render_markdown",
    "batch_stats",
    "connect",
    "count_cases",
    "finish_batch",
    "get_case",
    "init_db",
    "sha256_file",
    "start_batch",
    "upsert_case",
    "DIMENSION_LABELS_VI",
    "DIMENSIONS",
    "MISSING_GROUP",
    "Alert",
    "bucket_key",
    "bucketize",
    "check_thresholds",
    "detect_rising_trend",
    "fetch_records",
    "generate_report",
    "group_by_dimension",
    "incidence_table",
    "run_periodic_report",
    "Classification",
    "HistoryMatch",
    "RecurrenceAlert",
    "classify_error",
    "classify_new_error",
    "detect_family",
    "detect_recurrence",
    "evaluate_accuracy",
    "match_history",
    "ClosureBlockedError",
    "close_case",
    "get_closure",
    "init_feedback_loop",
    "log_suggestion_call",
    "positive_rate_by_quarter",
    "rating_coverage",
    "record_rating",
]
