"""F1: error_cases public API."""
from .backfill_fix import (
    FIX_BACKFILL_RULE,
    FIX_MARKERS_JP,
    FIX_MARKERS_VN,
    apply_backfill as apply_fix_backfill,
    extract_fix_segment,
    plan_backfill as plan_fix_backfill,
)
from .case_form import (
    FIELDS as CASE_FORM_FIELDS,
    REQUIRED_KEYS as CASE_FORM_REQUIRED_KEYS,
    ensure_form_batch,
    ensure_form_schema,
    find_duplicate as find_duplicate_case,
    lookup_error_code,
    looks_like_filled_form,
    parse_form_text,
    read_case,
    render_blank_form,
    split_error_code,
    submit_case as submit_form_case,
    validate_form,
)
from .column_map import (
    CODE_SCAN_COLUMNS,
    COLUMN_MAP,
    GREEN_SKIP_RGB,
    HISTORY_29_DATE_INDEX,
    HISTORY_29_MAP,
    SHEET_TYPES,
    analyze_row_codes,
    col_letter,
    extract_code_from_row,
    extract_code_from_text,
    history_no_dvd,
    is_green_skip,
    is_positive_mark,
    normalize_history_row,
    normalize_row,
    parse_date_cell,
    scan_free_text_codes,
)
from .completeness import (
    F3B_THRESHOLD,
    measure as measure_completeness,
    report as completeness_report,
)
from .glossary import (
    PARSERS,
    canonical_term,
    glossary_coverage,
    import_ccall_diag,
    import_ccall_old,
    import_glossary,
    init_glossary,
    lookup as glossary_lookup,
    norm_code,
    parse_ccall_diag,
    parse_ccall_old,
    seed_term_aliases,
    suggest_terms,
)
from .import_history import (
    SHEET_NAME as HISTORY_SHEET_NAME,
    SRC_EXTRACTED,
    SRC_KTD,
    SRC_MANUAL,
    backfill_error_code_i,
    backfill_error_code_i_extended,
    fill_occurred_at,
    import_history,
    list_ktd_dossiers,
    match_ktd_dossiers,
    parse_ktd_filename,
    write_manual_csv,
)
from .import_lsu_logs import (
    DIALECTS as LSU_LOG_DIALECTS,
    detect_lsu_dialect,
    import_lsu_log,
    import_lsu_tree,
    read_lsu_events,
)
from .investigation_tree import (
    BRANCH_LABELS_VI,
    BRANCHES,
    ChecklistItem,
    InvestigationTree,
    WhyNode,
    build_tree,
    build_why_chain,
    export_markdown,
    render_markdown,
)
from .store import (
    batch_stats,
    connect,
    count_cases,
    finish_batch,
    get_case,
    init_db,
    sha256_file,
    start_batch,
    upsert_case,
)
from .trend_analysis import (
    DIMENSION_LABELS_VI,
    DIMENSIONS,
    MISSING_GROUP,
    Alert,
    bucket_key,
    bucketize,
    check_thresholds,
    detect_rising_trend,
    fetch_records,
    generate_report,
    group_by_dimension,
    incidence_table,
    run_periodic_report,
)
from .auto_classifier import (
    Classification,
    HistoryMatch,
    RecurrenceAlert,
    classify_error,
    classify_new_error,
    detect_family,
    detect_recurrence,
    evaluate_accuracy,
    match_history,
)
from .feedback_loop import (
    ClosureBlockedError,
    close_case,
    get_closure,
    init_feedback_loop,
    log_suggestion_call,
    positive_rate_by_quarter,
    rating_coverage,
    record_rating,
)

__all__ = [
    "CODE_SCAN_COLUMNS",
    "COLUMN_MAP",
    "GREEN_SKIP_RGB",
    "HISTORY_29_DATE_INDEX",
    "HISTORY_29_MAP",
    "SHEET_TYPES",
    "analyze_row_codes",
    "col_letter",
    "extract_code_from_row",
    "scan_free_text_codes",
    "history_no_dvd",
    "is_green_skip",
    "is_positive_mark",
    "extract_code_from_text",
    "normalize_history_row",
    "normalize_row",
    "parse_date_cell",
    "CASE_FORM_FIELDS",
    "CASE_FORM_REQUIRED_KEYS",
    "ensure_form_batch",
    "ensure_form_schema",
    "find_duplicate_case",
    "lookup_error_code",
    "looks_like_filled_form",
    "parse_form_text",
    "read_case",
    "render_blank_form",
    "split_error_code",
    "submit_form_case",
    "validate_form",
    "F3B_THRESHOLD",
    "measure_completeness",
    "completeness_report",
    "FIX_BACKFILL_RULE",
    "FIX_MARKERS_VN",
    "FIX_MARKERS_JP",
    "extract_fix_segment",
    "plan_fix_backfill",
    "apply_fix_backfill",
    "PARSERS",
    "canonical_term",
    "glossary_coverage",
    "import_ccall_diag",
    "import_ccall_old",
    "import_glossary",
    "init_glossary",
    "glossary_lookup",
    "norm_code",
    "parse_ccall_diag",
    "parse_ccall_old",
    "seed_term_aliases",
    "suggest_terms",
    "HISTORY_SHEET_NAME",
    "backfill_error_code_i",
    "backfill_error_code_i_extended",
    "fill_occurred_at",
    "import_history",
    "list_ktd_dossiers",
    "match_ktd_dossiers",
    "parse_ktd_filename",
    "write_manual_csv",
    "SRC_EXTRACTED",
    "SRC_KTD",
    "SRC_MANUAL",
    "LSU_LOG_DIALECTS",
    "detect_lsu_dialect",
    "import_lsu_log",
    "import_lsu_tree",
    "read_lsu_events",
    "BRANCH_LABELS_VI",
    "BRANCHES",
    "ChecklistItem",
    "InvestigationTree",
    "WhyNode",
    "build_tree",
    "build_why_chain",
    "export_markdown",
    "render_markdown",
    "batch_stats",
    "connect",
    "count_cases",
    "finish_batch",
    "get_case",
    "init_db",
    "sha256_file",
    "start_batch",
    "upsert_case",
    "DIMENSION_LABELS_VI",
    "DIMENSIONS",
    "MISSING_GROUP",
    "Alert",
    "bucket_key",
    "bucketize",
    "check_thresholds",
    "detect_rising_trend",
    "fetch_records",
    "generate_report",
    "group_by_dimension",
    "incidence_table",
    "run_periodic_report",
    "Classification",
    "HistoryMatch",
    "RecurrenceAlert",
    "classify_error",
    "classify_new_error",
    "detect_family",
    "detect_recurrence",
    "evaluate_accuracy",
    "match_history",
    "ClosureBlockedError",
    "close_case",
    "get_closure",
    "init_feedback_loop",
    "log_suggestion_call",
    "positive_rate_by_quarter",
    "rating_coverage",
    "record_rating",
]
