"""RAG v2 core generic package."""

from .schema import DocumentElement, ElementType, ExtractionStatus, TableCell, TableData
from .adapters import DocumentConverterAdapter, ConversionContext, AdapterCapabilities, BaseDocumentConverterAdapter
from .converters import (
    TextDocumentConverterAdapter,
    HTMLDocumentConverterAdapter,
    PDFDocumentConverterAdapter,
    ExcelDocumentConverterAdapter,
    WordDocumentConverterAdapter,
    PowerPointDocumentConverterAdapter
)
from .registry import ConverterRegistry
from .chunking import DocumentChunk, StructureAwareChunker
from .index import LocalChunkIndex, SearchOptions, SearchResponse, SearchResult, SearchSummary
from .query_planning import (
    QueryExpander,
    RetrievalQueryPlan,
    RetrievalQueryVariant,
    build_query_plan,
    coerce_query_plan,
    identity_query_plan,
)
from .evidence import (
    EvidenceAnswerMode,
    EvidenceConfidence,
    EvidenceFacetCoverage,
    EvidenceObligationCoverage,
    EvidenceItem,
    EvidencePack,
    EvidencePackConfig,
    build_evidence_pack,
    format_evidence_for_prompt,
    evidence_pack_to_dict,
)
from .synthesis import (
    GroundedClaim,
    LocalSynthesisResult,
    ProviderSynthesisProvider,
    ProviderSynthesisRequest,
    ProviderSynthesisValidation,
    SynthesisPlan,
    build_synthesis_plan,
    format_provider_synthesis_contract,
    synthesize_evidence,
    synthesize_with_provider,
    validate_grounded_claims,
    validate_provider_synthesis_answer,
)
from .semantic import (
    DeterministicEmbeddingBackend,
    DeterministicRerankerBackend,
    EmbeddingBackend,
    FastEmbedEmbeddingBackend,
    FastEmbedRerankerBackend,
    RerankerBackend,
    SemanticBackendError,
    SemanticBackendUnavailable,
    SemanticCapability,
    SemanticModelDescriptor,
    UnavailableEmbeddingBackend,
    UnavailableRerankerBackend,
    cosine_similarity,
    normalize_vector,
    unavailable_embedding_backend,
)
from .eval_harness import (
    BenchmarkConfig,
    BenchmarkQuestion,
    BenchmarkResult,
    BenchmarkSummary,
    run_benchmark,
    format_benchmark_summary,
    benchmark_summary_to_dict,
)
from .pipeline import (
    IngestionItemReport,
    RagV2DevConfig,
    RagV2DevPipeline,
    RagV2IngestionReport,
    RagV2QueryResult,
    SourceSpec,
)

__all__ = [
    "DocumentElement",
    "ElementType",
    "ExtractionStatus",
    "TableCell",
    "TableData",
    "DocumentConverterAdapter",
    "ConversionContext",
    "AdapterCapabilities",
    "BaseDocumentConverterAdapter",
    "TextDocumentConverterAdapter",
    "HTMLDocumentConverterAdapter",
    "PDFDocumentConverterAdapter",
    "ExcelDocumentConverterAdapter",
    "WordDocumentConverterAdapter",
    "PowerPointDocumentConverterAdapter",
    "ConverterRegistry",
    "DocumentChunk",
    "StructureAwareChunker",
    "LocalChunkIndex",
    "SearchOptions",
    "SearchResponse",
    "SearchResult",
    "SearchSummary",
    "QueryExpander",
    "RetrievalQueryPlan",
    "RetrievalQueryVariant",
    "build_query_plan",
    "coerce_query_plan",
    "identity_query_plan",
    "EvidenceAnswerMode",
    "EvidenceConfidence",
    "EvidenceFacetCoverage",
    "EvidenceObligationCoverage",
    "EvidenceItem",
    "EvidencePack",
    "EvidencePackConfig",
    "build_evidence_pack",
    "format_evidence_for_prompt",
    "evidence_pack_to_dict",
    "GroundedClaim",
    "LocalSynthesisResult",
    "ProviderSynthesisProvider",
    "ProviderSynthesisRequest",
    "ProviderSynthesisValidation",
    "SynthesisPlan",
    "build_synthesis_plan",
    "format_provider_synthesis_contract",
    "synthesize_evidence",
    "synthesize_with_provider",
    "validate_grounded_claims",
    "validate_provider_synthesis_answer",
    "DeterministicEmbeddingBackend",
    "DeterministicRerankerBackend",
    "EmbeddingBackend",
    "FastEmbedEmbeddingBackend",
    "FastEmbedRerankerBackend",
    "RerankerBackend",
    "SemanticBackendError",
    "SemanticBackendUnavailable",
    "SemanticCapability",
    "SemanticModelDescriptor",
    "UnavailableEmbeddingBackend",
    "UnavailableRerankerBackend",
    "cosine_similarity",
    "normalize_vector",
    "unavailable_embedding_backend",
    "BenchmarkConfig",
    "BenchmarkQuestion",
    "BenchmarkResult",
    "BenchmarkSummary",
    "run_benchmark",
    "format_benchmark_summary",
    "benchmark_summary_to_dict",
    "IngestionItemReport",
    "RagV2DevConfig",
    "RagV2DevPipeline",
    "RagV2IngestionReport",
    "RagV2QueryResult",
    "SourceSpec",
]
